# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Scripter_config = debug
  TestProgram_config = debug
endif
ifeq ($(config),release)
  Scripter_config = release
  TestProgram_config = release
endif

PROJECTS := Scripter TestProgram

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Scripter:
ifneq (,$(Scripter_config))
	@echo "==== Building Scripter ($(Scripter_config)) ===="
	@${MAKE} --no-print-directory -C . -f Scripter.make config=$(Scripter_config)
endif

TestProgram: Scripter
ifneq (,$(TestProgram_config))
	@echo "==== Building TestProgram ($(TestProgram_config)) ===="
	@${MAKE} --no-print-directory -C . -f TestProgram.make config=$(TestProgram_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Scripter.make clean
	@${MAKE} --no-print-directory -C . -f TestProgram.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Scripter"
	@echo "   TestProgram"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"